#import './CategoryFragment.gql'

query GetCategory($slug: String!) {
  getCategory(slug: $slug) {
      ...Category
      products {
       
          id
          name
          slug
          price
          main_image_url
        }
     
  }
}
