mutation registerUser (
    $firstName: String!,
    $lastName: String!,
    $email: String!,
    $password: String!
    $passwordConfirmation: String!
) {
    registerUser (
        first_name: $firstName,
        last_name: $lastName,
        email: $email,
        password: $password
        password_confirmation : $passwordConfirmation
    ) {
        token_type
        expires_in
        access_token
        refresh_token   
    }
}